cd miFV_Binseg_1
run miFV_skoda_imbalanced_has0.m 
cd .. 
cd miFV_Binseg_2
run miFV_skoda_imbalanced_has0.m 
cd .. 
cd miFV_Binseg_3
run miFV_skoda_imbalanced_has0.m 
cd .. 
cd miFV_Binseg_4
run miFV_skoda_imbalanced_has0.m 
cd .. 
cd miFV_Binseg_5
run miFV_skoda_imbalanced_has0.m 
cd .. 
cd miFV_Binseg_6
run miFV_skoda_imbalanced_has0.m 
cd .. 
cd miFV_BottomUp_1
run miFV_skoda_imbalanced_has0.m 
cd .. 
cd miFV_BottomUp_2
run miFV_skoda_imbalanced_has0.m 
cd .. 
cd miFV_BottomUp_3
run miFV_skoda_imbalanced_has0.m 
cd .. 
cd miFV_BottomUp_4
run miFV_skoda_imbalanced_has0.m 
cd .. 
cd miFV_BottomUp_5
run miFV_skoda_imbalanced_has0.m 
cd .. 
cd miFV_BottomUp_6
run miFV_skoda_imbalanced_has0.m 
cd .. 
cd miFV_KCpA_1
run miFV_skoda_imbalanced_has0.m 
cd .. 
cd miFV_KCpA_2
run miFV_skoda_imbalanced_has0.m 
cd .. 
cd miFV_KCpA_3
run miFV_skoda_imbalanced_has0.m 
cd .. 
cd miFV_KCpA_4
run miFV_skoda_imbalanced_has0.m 
cd .. 
cd miFV_KCpA_5
run miFV_skoda_imbalanced_has0.m 
cd .. 
cd miFV_KCpA_6
run miFV_skoda_imbalanced_has0.m 
cd .. 
cd miFV_Pelt_1
run miFV_skoda_imbalanced_has0.m 
cd .. 
cd miFV_Pelt_2
run miFV_skoda_imbalanced_has0.m 
cd .. 
cd miFV_Pelt_3
run miFV_skoda_imbalanced_has0.m 
cd .. 
cd miFV_Pelt_4
run miFV_skoda_imbalanced_has0.m 
cd .. 
cd miFV_Pelt_5
run miFV_skoda_imbalanced_has0.m 
cd .. 
cd miFV_Pelt_6
run miFV_skoda_imbalanced_has0.m 
cd .. 
cd miFV_Window_1
run miFV_skoda_imbalanced_has0.m 
cd .. 
cd miFV_Window_2
run miFV_skoda_imbalanced_has0.m 
cd .. 
cd miFV_Window_3
run miFV_skoda_imbalanced_has0.m 
cd .. 
cd miFV_Window_4
run miFV_skoda_imbalanced_has0.m 
cd .. 
cd miFV_Window_5
run miFV_skoda_imbalanced_has0.m 
cd .. 
cd miFV_Window_6
run miFV_skoda_imbalanced_has0.m 
cd .. 
cd miFV_Dynp_1
run miFV_skoda_imbalanced_has0.m 
cd .. 
cd miFV_Dynp_2
run miFV_skoda_imbalanced_has0.m 
cd .. 
cd miFV_Dynp_3
run miFV_skoda_imbalanced_has0.m 
cd .. 
cd miFV_Dynp_4
run miFV_skoda_imbalanced_has0.m 
cd .. 
cd miFV_Dynp_5
run miFV_skoda_imbalanced_has0.m 
cd .. 
cd miFV_Dynp_6
run miFV_skoda_imbalanced_has0.m 
cd .. 
